import { Mail, UserSearch } from "lucide-react";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";
import { Button } from "@/components/ui/button";

const faqData = [
  {
    question: "How does Running Safer calculate the safety score?",
    answer: "Running Safer analyzes your Strava route data and cross-references it with human-annotated OpenStreetMap segments to give a comprehensive safety evaluation."
  },
  {
    question: "Is my Strava data secure?",
    answer: "Yes. Running Safer does not store or share your Strava data. Safety reports are generated from read-only data."
  },
  {
    question: "What should I do if a route has a low safety score?",
    answer: "A lower score typically means a route lacks pedestrian infrastructure (like sidewalks or lighting). Try reviewing the specific segments flagged as hazardous or trying an alternative route generated by Strava."
  },
  {
    question: "How accurate is OpenStreetMap data?",
    // Changed this string into a reusable JSX element
    answer: (
      <>
        OpenStreetMap data is crowdsourced and can vary in accuracy, read more about OpenStreetMap{" "}
        <a 
          href="https://wiki.openstreetmap.org/wiki/About_OpenStreetMap" 
          target="_blank" 
          rel="noopener noreferrer"
          className="text-primary underline underline-offset-4 hover:text-primary/80"
        >
          here
        </a>.
      </>
    )
  }
];

export const FAQ2 = () => (
  <div className="w-full py-20 px-4 sm:px-6 lg:py-40">
    <div className="container mx-auto">
      <div className="flex flex-col gap-10">
        <div className="flex text-center justify-center items-center gap-4 flex-col">
          <div className="flex gap-2 flex-col">
            <h4 className="text-3xl md:text-5xl tracking-tighter max-w-xl text-center font-regular">
                About Running Safer
            </h4>
            <p className="text-lg leading-relaxed tracking-tight text-muted-foreground max-w-xl text-center">
                Running Safer is a personal project by Carson Rivera to make runners aware of
                hazardous areas in their running routes. Strava routes are analyzed for pedestrian safety 
                using OpenStreetMap data, and users receive a safety score for each activity.
            </p>
          </div>
          <div>
            <Button className="gap-4" variant="outline" asChild>
                <a href="mailto:carsonrivera04@gmail.com">
                    Email<Mail className="w-4 h-4" />
                </a>
            </Button>
          </div>
          <div>
            <Button className="gap-4" variant="outline" asChild>
                <a href="https://www.linkedin.com/in/carsonrivera04/" target="_blank" rel="noopener noreferrer">
                    LinkedIn<UserSearch className="w-4 h-4" />
                </a>
            </Button>
          </div>
        </div>

        <div className="max-w-3xl w-full mx-auto">
          <Accordion type="single" collapsible className="w-full">
            {faqData.map((item, index) => (
              <AccordionItem key={index} value={"index-" + index}>
                <AccordionTrigger>
                  {item.question}
                </AccordionTrigger>
                <AccordionContent>
                  {item.answer}
                </AccordionContent>
              </AccordionItem>
            ))}
          </Accordion>
        </div>
      </div>
    </div>
  </div>
);